name: new_version
description: Check if your user has the most recent version of your Flutter app.
version: 0.3.4
homepage: https://github.com/Bazni/new_version

environment:
  sdk: ">=3.2.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus:
  http:
  html:
  url_launcher:
  collection:

dev_dependencies:
  flutter_test:
    sdk: flutter
